<a href="https://colab.research.google.com/github/bbcx-investments/notebooks/blob/main/fixed_income/duration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Example 
face_value = 100 # the face value of this bond is $100
maturity = 5
coupon_rate = 0.06 # annual coupon rate
yld = 0.05         # the yield is 5%

# coupon pays twice a year
n = int(maturity * 2)
coupon = coupon_rate*100 / 2 # coupon in $
cashFlows = [coupon] * n
cashFlows[-1] += 100
cashFlows

[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 103.0]

In [2]:
# discount factor at the bond yield
factor = 1 / (1 + yld / 2) ** np.arange(1, n + 1)
factor

array([0.97560976, 0.9518144 , 0.92859941, 0.90595064, 0.88385429,
       0.86229687, 0.84126524, 0.82074657, 0.80072836, 0.7811984 ])

In [3]:
# present value of the cash flow
pv = cashFlows * factor
pv

array([ 2.92682927,  2.85544319,  2.78579823,  2.71785193,  2.65156286,
        2.5868906 ,  2.52379571,  2.46223971,  2.40218509, 80.46343538])

In [4]:
# percent of the bond value that the pv of the cash flow contributes
pct = pv / (sum(pv))
pct

array([0.0280412 , 0.02735727, 0.02669002, 0.02603904, 0.02540394,
       0.02478434, 0.02417984, 0.02359009, 0.02301472, 0.77089954])

In [5]:
# year x pct: cash flows of the 'time to cash flow' multiplied by the percent above
year_pct = np.arange(0.5, (n + 1) / 2, 0.5) * pct
year_pct

array([0.0140206 , 0.02735727, 0.04003503, 0.05207809, 0.06350986,
       0.07435301, 0.08462944, 0.09436035, 0.10356624, 3.85449772])

In [14]:
# Macaulay duration equals to the sum over year x pct
macaulay = sum(year_pct).round(3)
print("The macaulay duration of this bond at ", maturity, "-year constant maturity with yield at ", yld*100, "% and ", coupon_rate*100, "% annual coupon rate", "is", macaulay)

The macaulay duration of this bond at  5 -year constant maturity with yield at  5.0 % and  6.0 % annual coupon rate is 4.408


In [13]:
# Modified duration
modified = macaulay / (1 + yld / 2)
print("The modified duration of this bond at ", maturity, "-year constant maturity with yield at ", yld*100, "% and ", coupon_rate*100, "% annual coupon rate", "is", modified.round(3))

The modified duration of this bond at  5 -year constant maturity with yield at  5.0 % and  6.0 % annual coupon rate is 4.3
